build:
    dependencies:
        before:
            -npm install
    environment:
      variables:
        JWT_SECRET: 'LONGESTSECRETEVER'
    nodes:
    coverage:
      tests:
        override:
          - command: npm test
            coverage:
              file: coverage/clover.xml
              format: clover
